name:                AleA
version:             0.1.0.0
github:              "githubuser/AleA"
license:             BSD3
author:              "Endless Arch"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/AleA#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- extra
- haskeline
# - liquidhaskell
- llvm-tf
- megaparsec
- pretty
- process
- split
- text
- text-builder

# - text == 2.0
# - text-builder-linear == 0.1

library:
  source-dirs: src
  dependencies:
  - llvm-tf

executables:
  alea:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AleA

tests:
  alea-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AleA
