name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.0.2'
        enable-stack: true
        stack-version: 'latest'
    
    - name: Install required packages
      run: |
        brew install llvm@13
    - name: Install dependencies
      run: |
        stack setup --reinstall
        stack build --only-dependencies
    - name: Build
      run: stack build
    - name: Run examples
      run: |
        stack run -- -v
        stack run -- -s examples/test
